### ISSUE TITLE
For Review

### ISSUE THREAD

**Issue by CaptainBawa** [CaptainBawa/DocBook-Back-End#14]
### We are 4 in a team

@CaptainBawa 
@ridabensalem 
@tomdan-ai 
@Christelle-12 

Kanban Board Link (https://github.com/CaptainBawa/DocBook-Back-End/projects/1)
Frontend Link (https://github.com/CaptainBawa/DocBook-Front-End)

### Screenshot

![Capture](https://github.com/CaptainBawa/DocBook-Back-End/assets/82339317/eaeea537-8eee-46bb-9231-a025a04655b1)

**Comment by Meltrust** [comment]
Hi @CaptainBawa,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, pointed, and have descriptions. ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
